# Generated by Django 6.0 on 2025-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField()),
                ('Date', models.DateField()),
                ('email', models.TextField()),
            ],
        ),
    ]
